package gui
import ("bytes";"image/color";"io";"os";"path/filepath";"fyne.io/fyne/v2";"fyne.io/fyne/v2/app";"fyne.io/fyne/v2/canvas";"fyne.io/fyne/v2/container";"fyne.io/fyne/v2/dialog";"fyne.io/fyne/v2/layout";"fyne.io/fyne/v2/theme";"fyne.io/fyne/v2/widget";"SendDrop/internal/config";"SendDrop/internal/qrcode";"SendDrop/internal/server";"SendDrop/internal/storage")
type Window struct{app fyne.App;window fyne.Window;server *server.Server;storage *storage.Manager;statusBar *StatusBar;qrWidget *QRWidget;fileList *widget.List;files []storage.FileInfo;startBtn *widget.Button;uploadBtn *widget.Button;copyBtn *widget.Button;theme *CustomTheme}
func NewWindow()*Window{a:=app.NewWithID("com.senddrop.app");ct:=NewCustomTheme(true);a.Settings().SetTheme(ct);w:=a.NewWindow("SendDrop");w.Resize(fyne.NewSize(600,600));w.CenterOnScreen();sd:=filepath.Join(filepath.Dir(os.Args[0]),config.AppConfig.ShareDir);sm,_:=storage.NewManager(sd);srv:=server.NewServer(config.AppConfig.Port,config.AppConfig.IP,sd);win:=&Window{app:a,window:w,server:srv,storage:sm,theme:ct,files:[]storage.FileInfo{}};win.buildUI();return win}
func (w*Window)buildUI(){w.statusBar=NewStatusBar();w.statusBar.SetIP(w.server.GetLocalIP());w.statusBar.SetPort(config.AppConfig.Port);w.qrWidget=NewQRWidget();w.fileList=widget.NewList(func()int{return len(w.files)},func()fyne.CanvasObject{return container.NewHBox(widget.NewIcon(theme.FileIcon()),widget.NewLabel("filename"),layout.NewSpacer(),widget.NewButtonWithIcon("",theme.DownloadIcon(),nil),widget.NewButtonWithIcon("",theme.DeleteIcon(),nil))},func(id int,obj fyne.CanvasObject){if id>=len(w.files){return};file:=w.files[id];hbox:=obj.(*fyne.Container);label:=hbox.Objects[1].(*widget.Label);label.SetText(file.Name)});w.startBtn=widget.NewButtonWithIcon("START SERVER",theme.MediaPlayIcon(),func(){w.toggleServer()});w.startBtn.Importance=widget.HighImportance;w.uploadBtn=widget.NewButtonWithIcon("UPLOAD FILE",theme.UploadIcon(),func(){w.uploadFile()});w.uploadBtn.Importance=widget.MediumImportance;w.uploadBtn.Disable();w.copyBtn=widget.NewButtonWithIcon("COPY LINK",theme.ContentCopyIcon(),func(){w.copyLink()});w.copyBtn.Importance=widget.LowImportance;w.copyBtn.Disable();title:=canvas.NewText("SendDrop",color.White);title.TextSize=20;title.TextStyle=fyne.TextStyle{Bold:true};header:=container.NewHBox(title,layout.NewSpacer());controls:=container.NewVBox(container.NewHBox(w.startBtn,w.uploadBtn,w.copyBtn));flc:=container.NewBorder(container.NewHBox(widget.NewLabelWithStyle("Files:",fyne.TextAlignLeading,fyne.TextStyle{Bold:true})),nil,nil,nil,container.NewVScroll(w.fileList));supportBtn:=widget.NewHyperlink("❤️ Support Author",nil);supportBtn.Alignment=fyne.TextAlignCenter;versionLabel:=widget.NewLabel("v1.0.0");versionLabel.Alignment=fyne.TextAlignTrailing;versionLabel.TextStyle=fyne.TextStyle{Italic:true};footer:=container.NewHBox(supportBtn,layout.NewSpacer(),versionLabel);content:=container.NewBorder(container.NewVBox(header,widget.NewSeparator(),w.statusBar),footer,nil,nil,container.NewVBox(container.NewCenter(w.qrWidget),controls,widget.NewSeparator(),flc));w.window.SetContent(content)}
func (w*Window)toggleServer(){if w.server.IsOnline(){w.server.Stop();w.startBtn.SetText("START SERVER");w.startBtn.SetIcon(theme.MediaPlayIcon());w.uploadBtn.Disable();w.copyBtn.Disable();w.statusBar.SetOnline(false);w.qrWidget.SetQR(nil)}else{w.server.Start();w.startBtn.SetText("STOP SERVER");w.startBtn.SetIcon(theme.MediaStopIcon());w.uploadBtn.Enable();w.copyBtn.Enable();w.statusBar.SetOnline(true);w.statusBar.SetIP(w.server.GetLocalIP());url:=w.server.GetURL();qrData,_:=qrcode.GenerateQR(url,200);w.qrWidget.SetQR(qrData)}}
func (w*Window)uploadFile(){dialog.ShowFileOpen(func(r fyne.URIReadCloser,e error){if e!=nil||r==nil{return};defer r.Close();fn:=filepath.Base(r.URI().Path());d,_:=io.ReadAll(r);w.storage.SaveFile(fn,bytes.NewReader(d));w.refreshFileList();dialog.ShowInformation("Success","File uploaded: "+fn,w.window)},w.window)}
func (w*Window)copyLink(){if!w.server.IsOnline(){return};url:=w.server.GetURL();w.window.Clipboard().SetContent(url);dialog.ShowInformation("Link Copied","Link copied to clipboard:\n"+url,w.window)}
func (w*Window)refreshFileList(){f,_:=w.storage.ListFiles();w.files=f;w.fileList.Refresh()}
func (w*Window)Run(){w.window.ShowAndRun()}
